events {
worker_connections 1024;
}
http {
include /etc/nginx/mime.types;
default_type application/octet-stream;
server {
listen 80;
server_name localhost;
root /var/lib/nginx/html;
index index.html;
location / {
try_files $uri $uri/ =404;
}
# Error and access logs
error_log /var/log/nginx/error.log;
access_log /var/log/nginx/access.log;
}
}