apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web # metadata.labels.app ,in python: metadata['labels']['app']
    tier: frontend
spec: 
  containers: # in python: containers = [ {name:nginx, "image": "nginx:1.21", ports: [containerPort: 80]} , {name:redis}]
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
  - name: redis
    image: redis:6.2
    ports:
    - containerPort: 6379